Testing
murrcha/it-univer pull request #12
Opened 2019-01-24 18:23 UTC by murrcha

2019-01-25 10:37 UTC, RomanPozdeev requested changes

2019-01-25 10:37 UTC, RomanPozdeev commented on app/src/test/java/com/kkaysheva/ituniver/domain/tools/ContactInfoRepositoryStubImpl.java
> +        repository.clear();
Этот метод будет выполнен когда будет вызван, а не когда на него подпишутся. Поэтому этот метод должен выглядеть как return Completable.fromAction

2019-01-25 10:37 UTC, RomanPozdeev commented on app/src/test/java/com/kkaysheva/ituniver/domain/tools/ContactInfoRepositoryStubImpl.java
> +        repository.clear();
Для душевного спокойствия я бы и с синглами методы переписал

2019-01-25 12:12 UTC, murrcha commented on app/src/test/java/com/kkaysheva/ituniver/domain/tools/ContactInfoRepositoryStubImpl.java
> +        repository.clear();
Да, изначально это был костыль, исправила на отложенный вызов

2019-01-25 12:14 UTC, murrcha commented on app/src/test/java/com/kkaysheva/ituniver/domain/tools/ContactInfoRepositoryStubImpl.java
> +        repository.clear();
На душе стало спокойнее =)

2019-01-28 04:46 UTC, RomanPozdeev approved these changes

2019-01-29 06:22 UTC, merged