Домашнее задание
murrcha/it-univer pull request #3
Opened 2018-11-23 07:33 UTC by murrcha

2018-11-23 08:42 UTC, goblinr requested changes

2018-11-23 08:42 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/Contact.java
> +    }
Лучше придерживаться концепции "неизменяемых" объектов https://docs.oracle.com/javase/tutorial/essential/concurrency/imstrat.html

2018-11-23 08:42 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        setRetainInstance(true);
Не стоит использовать `setRetainInstance(true)` здесь. В данном случае это приведет к утечке памяти.

2018-11-23 08:42 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        Contact contact = ContactFetcher.getContactById(this.contactId, Objects.requireNonNull(getActivity()));
Чтение контакта на главном потоке программы. Это неприемлемо, с точки зрения отзывчивого UI.

2018-11-23 08:42 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        Contact contact = ContactFetcher.getContactById(this.contactId, Objects.requireNonNull(getActivity()));
Так же нее вижу, что бы спрашивалось разрешение пользователя на чтение контактов, перед этим.

2018-11-23 08:42 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        outState.putInt(CONTACT_ID, contactId);
`contactId` не обязательно сохранять в `onSaveInstanceState`, т.к. ты уже получаешь его с помощью `getArguments`

2018-11-23 08:42 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +        List<Contact> contacts = ContactFetcher.getContacts(Objects.requireNonNull(getActivity()));
Чтение контактов на главном потоке программы.
Не спрашиваются разрешение на чтение контактов.

2018-11-23 08:42 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +        setRetainInstance(true);
Утечка памяти из-за Retained Fragment'а

2018-11-23 08:42 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +                .replace(R.id.fragment_container, contactsFragment)
После поворота экрана, если мы были в деталях контакта до этого, это приведет к тому что пользователь вновь окажется на списке контактов.

2018-11-23 08:42 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +                .addToBackStack(null)
Здесь точно будет утечка памяти из-за того что `ContactFragment` - Retained. Retained фрагменты нельзя класть в бэкстэк.

2018-11-23 08:45 UTC, RomanPozdeev requested changes

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        Contact contact = ContactFetcher.getContactById(this.contactId, Objects.requireNonNull(getActivity()));
Вместо Objects.requireNonNull(getActivity()) лучше использовать requireContext()

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        if (contact != null) {
contact может быть null?

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +    public interface CLickContactCallback {
ClickContactCallback

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +        List<Contact> contacts = ContactFetcher.getContacts(Objects.requireNonNull(getActivity()));
requireActivity()

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +        if (contacts != null && !contacts.isEmpty()) {
getContacts судя по коду всегда возвращает не null значение

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +    protected void onCreate(Bundle savedInstanceState) {
protected void onCreate(Bundle savedInstanceState)  -> protected void onCreate(@Nullable Bundle savedInstanceState)

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +        Bundle args = new Bundle();
Всю логику по созданию фрагмента перенести в код фрагмента - в статический метод newInstance(...). Это общепринятый способ, кроме того так достигается инкапсуляция передачи аргументов в фрагмент. Как золотое правило - new BlaBlaFragment() - должен вызываться только внутри самого фрагмента.

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/AndroidManifest.xml
> +        android:allowBackup="true"
На этот параметр стоит обращать особое внимание, он может быть как источником неожидаемого поведения так и проблем с безопастностью. И если не нужно иное, лучше ставить его в false

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        if (savedInstanceState != null) {
У нас возможна ситуация когда меняется contactId?

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        setRetainInstance(true);
retain фрагменты лучше не использовать, или делать их без вью.

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +        adapter.setOnClickListener(new ContactAdapter.OnItemClickListener() {
обычно я делаю адаптеры которым в конструктор передается Listener, но так в принципе тоже можно

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +        adapter.setOnClickListener(new ContactAdapter.OnItemClickListener() {
Лучше перейти на лямбды. Для этого добавь в app.gradle
android {
     compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +        setRetainInstance(true);
то же замечание что и по предыдущему фрагменту

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +        fragmentManager = getSupportFragmentManager();
Обычно делают так - если savedInstanceState == null - то добавляют фрагмент, если нет - то FragmentManager сам все восстановит

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +    private FragmentManager fragmentManager;
FragmentManager всегда можно получить через getSupportFragmentManager()

2018-11-23 08:45 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +    private Fragment contactFragment;
как правило ссылка на contactFragment - не нужна

2018-11-24 18:58 UTC, murrcha commented on app/src/main/AndroidManifest.xml
> +        android:allowBackup="true"
исправила на false

2018-11-24 19:00 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/Contact.java
> +    }
убрала все сеттеры и дефолтный конструктор, сделала все поля final, оставила 1 конструктор с параметрами

2018-11-24 19:00 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        if (savedInstanceState != null) {
удалила сохранение в Bundle

2018-11-24 19:02 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        setRetainInstance(true);
видимо изначально неправильно запомнила, на слайде была надпись, что обязательно использовать, только в контексте фрагментов без вью, но у меня сохранилось без контекста )
убрала setRetainInstance(true)

2018-11-24 19:02 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        setRetainInstance(true);
убрала setRetainInstance(true)

2018-11-24 19:03 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        Contact contact = ContactFetcher.getContactById(this.contactId, Objects.requireNonNull(getActivity()));
исправила на requireContext()

2018-11-24 19:03 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        Contact contact = ContactFetcher.getContactById(this.contactId, Objects.requireNonNull(getActivity()));
Вынесла чтение контактов в отдельный поток
Добавила запрос разрешения на чтение контактов

2018-11-24 19:05 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        if (contact != null) {
теперь уже может, убрала дефолтный конструктор и сеттеры из модели, сказали сделать immutable, потому теперь либо ссылка, либо null

2018-11-24 19:05 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        outState.putInt(CONTACT_ID, contactId);
убрала сохранение в onSaveInstanceState

2018-11-24 19:06 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +    public interface CLickContactCallback {
Исправила опечатку

2018-11-24 19:08 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +        adapter.setOnClickListener(new ContactAdapter.OnItemClickListener() {
Передачу слушателя в конструктор адаптера попробую, не думала, что так можно
Добавила java 8, исправила анонимные на лямбды

2018-11-24 19:08 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +        List<Contact> contacts = ContactFetcher.getContacts(Objects.requireNonNull(getActivity()));
исправила

2018-11-24 19:08 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +        List<Contact> contacts = ContactFetcher.getContacts(Objects.requireNonNull(getActivity()));
Вынесла чтение в отдельный поток
Добавила запрос разрешения на чтение контактов

2018-11-24 19:09 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +        if (contacts != null && !contacts.isEmpty()) {
Убрала проверку на null

2018-11-24 19:11 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +        setRetainInstance(true);
исправила

2018-11-24 19:11 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +        setRetainInstance(true);
убрала setRetainInstance

2018-11-24 19:12 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +    private FragmentManager fragmentManager;
исправила

2018-11-24 19:12 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +    private Fragment contactFragment;
убрала

2018-11-24 19:12 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +    protected void onCreate(Bundle savedInstanceState) {
добавила аннотацию

2018-11-24 19:12 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +        fragmentManager = getSupportFragmentManager();
сделала через savedInstanceState == null добавление фрагмента

2018-11-24 19:13 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +                .replace(R.id.fragment_container, contactsFragment)
исправила

2018-11-24 19:13 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +        Bundle args = new Bundle();
добавила static методы newInstance

2018-11-24 19:14 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +                .addToBackStack(null)
убрала setRetainInstance

2018-11-24 20:02 UTC, goblinr requested changes

2018-11-24 20:02 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +    private class LoaderThread extends Thread {
объекты класса `Thread` - являются рутовыми объектами для сборщика мусора, поэтому все ссылки связанные с ними - не будут собраны пока поток не закончит свою работу.
Т.к. класс `LoaderThread` - inner(внутренний), т.е. имеет доступ до инстанса внешнего класса(в данном случае это `ContactFragment`), а так же ты передаешь внутрь него еще и ссылку на `Activity` - ни `Activity` ни `ContactFragment` не будут собраны сборщиком мусора, пока будет работать поток, за это время может произойти массу вещей, например поворот экрана - в этом случае произойдет крэш приложения и утечка памяти на время работы потока, т.к. система уничтожит старую активность с фрагментом, но т.к. поток еще работает - ссылки будут оставться живыми, `loadContact` вызовится у старого фрагмента, у которого будут уничтожены все вьюшки, соответственно программа попытается установить текст в уже уничтоженные вьюшки, что и приведет к крэшу приложения.

2018-11-24 20:02 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        loaderThread = null;
Ссылку на поток следует очистить до `super` и стоит делать это не в `onDetach`, а в `onDestroyView`

2018-11-24 20:02 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +    private class LoaderThread extends Thread {
1) Следует использовать вложенный класс вместо внутреннего.
2) Ссылку на контекст сделать слабой, что бы не возникало удержание ссылки после уничтожения активности.

2018-11-24 20:02 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +            new Handler(Looper.getMainLooper()).post(() -> loadContact(contact));
Инициализацию `Handler` следует вынести в конструктор

2018-11-24 20:02 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +    private class LoaderThread extends Thread {
Все выше сказанное справедливо и здесь

2018-11-24 20:02 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +        loaderThread = null;
См. комментарии выше

2018-11-25 16:59 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +    private class LoaderThread extends Thread {
Спасибо, за подробное разъяснение :) 

1) Сделала static class LoaderThread чтобы не было зависимости от экземпляра фрагмента
2) Добавила контекст в WeakReference<T>, добавила проверку на null чтобы не трогать вьюшки, которых уже может не быть

2018-11-25 16:59 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +        loaderThread = null;
Исправила

2018-11-25 16:59 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +            new Handler(Looper.getMainLooper()).post(() -> loadContact(contact));
Вынесла в конструктор

2018-11-25 17:00 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +    private class LoaderThread extends Thread {
Исправила

2018-11-25 17:00 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactsFragment.java
> +        loaderThread = null;
Исправила

2018-11-26 06:55 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +    private class LoaderThread extends Thread {
Не нравится мне получение ссылки на фрагмент в самом потоке
Правильнее будет передавать интерфейс, реализуемый фрагментом, в конструктор потока?
Например, OnLoadCompleted

2018-11-26 07:00 UTC, RomanPozdeev requested changes

2018-11-26 07:00 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +            if (fragment != null && fragment instanceof ContactFragment) {
достаточно instanceOf - он корректно обрабатывает ситуацию с Null

2018-11-26 15:19 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +    private class LoaderThread extends Thread {
Сейчас главное, что бы работало как надо и без багов. Все равно потом все переделаете на RxJava.

2018-11-26 15:20 UTC, goblinr approved these changes

2018-11-26 16:33 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +            if (fragment != null && fragment instanceof ContactFragment) {
убрала проверку на null

2018-11-27 07:21 UTC, RomanPozdeev approved these changes

2018-11-27 07:22 UTC, merged