Домашнее задание 2
murrcha/it-univer pull request #4
Opened 2018-11-28 07:43 UTC by murrcha

Еще не успела подключить чичероне для навигации по фрагментам, добавлю вечером
Подключила Moxy, добавила презентеры для фрагментов
Нужно ли сделать презентеры глобальными, чтобы они не зависели от жц фрагментов?

2018-11-28 07:56 UTC, goblinr requested changes

2018-11-28 07:56 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactFragmentPresenter.java
> +        private final ContactFragmentPresenter contactFragmentPresenter;
У презентера тоже есть свой жизненный цикл. Стоит использовать `WeakReference`

2018-11-28 07:56 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/view/ContactFragmentView.java
> +    void showProgress(boolean isLoading);
Нужно указать стратегии для всех методов

2018-11-28 07:56 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/view/ContactsFragmentView.java
> +    void showProgress(boolean isLoading);
Нужно указать стратегии

2018-11-28 07:56 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/view/MainView.java
> +    void replaceContactFragment();
Стратегии

2018-11-28 07:56 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactsFragmentPresenter.java
> +        private final ContactsFragmentPresenter contactsFragmentPresenter;
У презентера тоже есть свой жизненный цикл. Стоит использовать `WeakReference`

2018-11-28 08:05 UTC, RomanPozdeev requested changes

2018-11-28 08:05 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +    ContactFragmentPresenter contactFragmentPresenter;
просто presenter, в MVP у тебя в теории других их быть не должно

2018-11-28 08:05 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +            contactFragmentPresenter.updateUI(contactId);
не совсем удачное название метода

2018-11-28 08:05 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactFragmentPresenter.java
> +    static class LoadContactAsyncTask extends AsyncTask<Integer, Void, Contact> {
тут как вариант - если не делать static - то и this передавать не придется. таску хорошо бы в onDestroy презентера отменять

2018-11-28 08:05 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/presenter/MainActivityPresenter.java
> +        getViewState().addContactsFragment();
более подходящий для этих целей метод onFirstViewAttach, но на самом деле все же лучше оставить в активити. Презентеры в Moxy не переживают смерть процесса

2018-11-28 08:05 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/view/ContactFragmentView.java
> +    void loadContact(Contact contact);
Обязательно поставить стратегии над методами

2018-11-28 18:15 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactFragmentPresenter.java
> +        private final ContactFragmentPresenter contactFragmentPresenter;
Добавила WeakReference

2018-11-28 18:16 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactsFragmentPresenter.java
> +        private final ContactsFragmentPresenter contactsFragmentPresenter;
Добавила WeakReference

2018-11-28 18:17 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/view/ContactFragmentView.java
> +    void showProgress(boolean isLoading);
Добавила
@StateStrategyType(SingleStateStrategy.class)
void loadContact(Contact contact);

@StateStrategyType(SingleStateStrategy.class)
void showProgress(boolean isLoading);

2018-11-28 18:18 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/view/ContactsFragmentView.java
> +    void showProgress(boolean isLoading);
Добавила

@StateStrategyType(SingleStateStrategy.class)
void loadContacts(List<Contact> contacts);

@StateStrategyType(SingleStateStrategy.class)    
void showProgress(boolean isLoading);

2018-11-28 18:18 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +    ContactFragmentPresenter contactFragmentPresenter;
Исправила на просто presenter

2018-11-28 18:19 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +            contactFragmentPresenter.updateUI(contactId);
Исправила на load вместо updateUI

2018-11-28 18:22 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactFragmentPresenter.java
> +    static class LoadContactAsyncTask extends AsyncTask<Integer, Void, Contact> {
Пробовала убрать static, в Android Studio выделяется и ругается на memory lick
Добавила WeakReference для presenter
Добавила отмену в onDestroy

    @Override
    public void onDestroy() {
        task.cancel(true);
        task = null;
        super.onDestroy();
    }

2018-11-28 18:22 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/view/ContactFragmentView.java
> +    void loadContact(Contact contact);
Проставила

    @StateStrategyType(SingleStateStrategy.class)
    void loadContact(Contact contact);

    @StateStrategyType(SingleStateStrategy.class)
    void showProgress(boolean isLoading);

2018-11-28 19:15 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/presenter/MainActivityPresenter.java
> +        getViewState().addContactsFragment();
То есть нет смысла делать добавление и смену фрагмента через презентер?

2018-11-29 16:59 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/presenter/MainActivityPresenter.java
> +        getViewState().addContactsFragment();
Убрала presenter для activity
Добавила navigator в activity для добавления первого экрана

```
if (savedInstanceState == null) {
            navigator.applyCommands(new Command[] {
                    new Replace(new Screens.ContactsScreen())
            });
        }
```

2018-11-29 17:01 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/view/MainView.java
> +    void replaceContactFragment();
Убрала presenter для activity
Добавила navigator в activity для добавления первого экрана

```
if (savedInstanceState == null) {
            navigator.applyCommands(new Command[] {
                    new Replace(new Screens.ContactsScreen())
            });
        }
```

Для перехода на детальный добавила в presenter первого фрагмента router

```
public void onForwardCommandClick(int contactId) {
        router.navigateTo(new Screens.ContactScreen(contactId));
    }
```

2018-11-30 04:16 UTC, goblinr requested changes

2018-11-30 04:16 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/App.java
> +    public static App INSTANCE;
Uppercase делай только для констант. В данном случае `INSTANCE` - это не константа

2018-11-30 04:16 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +            });
Эту команду можно послать в презентере в `onFirstViewAttach`

2018-11-30 04:16 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactsFragmentPresenter.java
> +        router = App.INSTANCE.getRouter();
`router` можно инициализировать в конструкторе и сделать его `final`

2018-11-30 04:16 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactsFragmentPresenter.java
> +        router = null;
`router` не обязательно обнулять, скоуп его жизни больше чем у презентера

2018-11-30 04:16 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/view/ContactFragmentView.java
> +    void showProgress(boolean isLoading);
`SingleStateStrategy` - очищает всю очередь команд, именно такое поведение требуется? Т.е. если до этого в очереди была команда для `loadContact` и придет команда для `showProgress` - `loadContact` затрется и останется только `showProgress`

2018-11-30 04:16 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/view/ContactsFragmentView.java
> +    void showProgress(boolean isLoading);
`SingleStateStrategy` - очищает всю очередь команд, именно такое поведение требуется? Т.е. если до этого в очереди была команда для `loadContacts` и придет команда для `showProgress` - `loadContacts` затрется и останется только `showProgress`

2018-11-30 17:22 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/view/ContactFragmentView.java
> +    void showProgress(boolean isLoading);
То есть чтобы не терять команды и не дублировать одинаковые нужно использовать `AddToEndSingleStrategy` , чтобы при повороте устройства они сработали снова?

    @StateStrategyType(AddToEndSingleStrategy.class)
    void loadContact(Contact contact);

    @StateStrategyType(AddToEndSingleStrategy.class)
    void showProgress(boolean isLoading);

2018-11-30 17:25 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/view/ContactsFragmentView.java
> +    void showProgress(boolean isLoading);
Требуется чтобы команды остались в том порядке, в котором пришли первый раз и воспроизвелись при перевороте. Исправила на `AddToEndSingleStrategy` 

    @StateStrategyType(AddToEndSingleStrategy.class)
    void loadContacts(List<Contact> contacts);

    @StateStrategyType(AddToEndSingleStrategy.class)
    void showProgress(boolean isLoading);

2018-11-30 17:27 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactsFragmentPresenter.java
> +        router = null;
Убрала `router = null;`

2018-11-30 17:27 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactsFragmentPresenter.java
> +        router = App.INSTANCE.getRouter();
Добавила инициализацию в конструктор 
Добавила final

2018-11-30 17:28 UTC, RomanPozdeev requested changes

2018-11-30 17:28 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/Screens.java
> +        private int contactId;
Final

2018-11-30 17:28 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactFragmentPresenter.java
> +        public LoadContactAsyncTask(ContactFragmentPresenter presenter) {
Тут на самом деле большой вопрос а нужен ли weakreference

2018-11-30 17:28 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/presenter/MainActivityPresenter.java
> +    protected void onFirstViewAttach() {
Этот метод вызывается и в случае восстановления процесса. Так что надо подумать а нужна ли здесь навигация

2018-11-30 17:29 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +            });
Перенесла в presenter:

    @Override
    protected void onFirstViewAttach() {
        super.onFirstViewAttach();
        navigateToContacts();
    }

    private void navigateToContacts() {
        getViewState().navigateTo(new Screens.ContactsScreen());
    }

Стратегия:

    @StateStrategyType(OneExecutionStateStrategy.class)
    void navigateTo(Screens.ContactsScreen screen);

2018-11-30 17:30 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/App.java
> +    public static App INSTANCE;
Исправила на `instance`

2018-11-30 17:33 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/view/ContactFragmentView.java
> +    void loadContact(Contact contact);
Изменила на `AddToEndSingleStrategy`

2018-11-30 17:41 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/presenter/MainActivityPresenter.java
> +    protected void onFirstViewAttach() {
Возможно неудачное название, по сути не навигация а открытие первого экрана со списком
Изначально вызов навигатора был в onCreate activity так
      ```
       if (savedInstanceState == null) {
            navigator.applyCommands(new Command[] {
                    new Replace(new Screens.ContactsScreen())
            });
        }
```
по замечанию Романа Р. 

> Эту команду можно послать в презентере в onFirstViewAttach

перенесла в presenter

Все таки как лучше?

2018-11-30 17:44 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/presenter/MainActivityPresenter.java
> +    protected void onFirstViewAttach() {
Ну тебе решать как твое приложение будет жить после восстановления. Можно 'доработать' презентер чтобы он знал что на самом деле произошло

2018-11-30 17:52 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactFragmentPresenter.java
> +        public LoadContactAsyncTask(ContactFragmentPresenter presenter) {
если убрать static, то не нужно передавать presenter
только Android Studio подчеркивает и пишет memory lick
или я что-то не учитываю или не об этом?

2018-11-30 18:43 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/presenter/MainActivityPresenter.java
> +    protected void onFirstViewAttach() {
То есть добавить проверку в presenter?
    private void navigateToContacts() {
        if (!isInRestoreState(getViewState())) {
            getViewState().navigateTo(new Screens.ContactsScreen());
        }
    }

2018-12-01 05:52 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactFragmentPresenter.java
> +        public LoadContactAsyncTask(ContactFragmentPresenter presenter) {
В данном случае это не существенно. Презентер по сути мелкий объект в памяти и если он поживет на несколько секунд дольше ничего не случится. Тем более ты тачку отменяешь

2018-12-01 05:52 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactFragmentPresenter.java
> +        public LoadContactAsyncTask(ContactFragmentPresenter presenter) {
В данном случае это не существенно. Презентер по сути мелкий объект в памяти и если он поживет на несколько секунд дольше ничего не случится. Тем более ты тачку отменяешь

2018-12-01 11:23 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/Screens.java
> +        private int contactId;
Добавила

2018-12-02 11:30 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +            });
Имелось в виду, что `MainActivity` ничего не должа знать о сущьности `Router`, команды навигации должны инициироваться либо в Presenter, либо в Модели. Так же нужно не забыть, что `onFirstViewAttach` вызывается всегда, т.е. даже при восстановлении `MainActivity` после смены конфигурации. Поэтому можно воспользоваться специалтьным методом презентера `isInRestoreState`

2018-12-02 15:38 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactFragment.java
> +            contactFragmentPresenter.updateUI(contactId);
fix: fetchContact

2018-12-02 15:39 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactFragmentPresenter.java
> +    static class LoadContactAsyncTask extends AsyncTask<Integer, Void, Contact> {
fix: remove static and weak reference

2018-12-02 15:41 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/presenter/MainActivityPresenter.java
> +        getViewState().addContactsFragment();
Теперь в презентере так:

    @Override
    protected void onFirstViewAttach() {
        super.onFirstViewAttach();
        if (!isInRestoreState(getViewState())) {
            addContactsScreen();
        }
    }

2018-12-02 15:42 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/MainActivity.java
> +            });
Добавила в презентер:

    @Override
    protected void onFirstViewAttach() {
        super.onFirstViewAttach();
        if (!isInRestoreState(getViewState())) {
            addContactsScreen();
        }
    }

    private void addContactsScreen() {
        router.replaceScreen(new Screens.ContactsScreen());
    }

2018-12-02 15:42 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/presenter/ContactFragmentPresenter.java
> +        public LoadContactAsyncTask(ContactFragmentPresenter presenter) {
Убрала static и WeakReference

2018-12-02 15:43 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/presenter/MainActivityPresenter.java
> +    protected void onFirstViewAttach() {
В презентере:

    @Override
    protected void onFirstViewAttach() {
        super.onFirstViewAttach();
        if (!isInRestoreState(getViewState())) {
            addContactsScreen();
        }
    }

    private void addContactsScreen() {
        router.replaceScreen(new Screens.ContactsScreen());
    }

2018-12-03 04:01 UTC, goblinr approved these changes

2018-12-03 04:01 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/presenter/MainActivityPresenter.java
> +        router.replaceScreen(new Screens.ContactsScreen());
Думаю, здесь имеет смысл использовать `newRootScreen` - т.к. экран списка контактов у нас является рутовым по дизайну.

2018-12-03 08:19 UTC, RomanPozdeev approved these changes

2018-12-03 08:24 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/presenter/MainActivityPresenter.java
> +        router.replaceScreen(new Screens.ContactsScreen());
Исправлю в следующем коммите

2018-12-03 08:24 UTC, merged