ДЗ-3: DiffUtil, ItemDecoration, SerachView
murrcha/it-univer pull request #5
Opened 2018-12-04 19:08 UTC by murrcha

Предварительный результат

2018-12-06 04:31 UTC, goblinr requested changes

2018-12-06 04:31 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/adapter/ContactAdapter.java
> +    private final List<Contact> contactsFull = new ArrayList<>();
Подход - сначала загрузить все данные, а потом уже фильтровать их, подходит для ситуации, когда ты полностью уверен, что объем всех данных не приведет к нежелательным последствиям(вроде OutOfMemory, долгое время выполнения фильтрации из-за обилия данных и пр.). В противном случае, необходимо фильтровать данные на уровне источника данных, т.е. БД(тем более в БД есть механизмы оптимизации поиска). В данном конкретном случае, скорее всего на большинстве устройств памяти хватит, но бывают крайние ситуации.

Поэтому, я считаю, что правильнее будет реализовать поиск на уровне `ContentResolver`

2018-12-06 04:31 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/adapter/ContactAdapter.java
> +        new Thread(() -> {
Поток следует интеруптить, на `onDestroyView` фрагмента.

2018-12-06 04:31 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/adapter/ContactItemDecoration.java
> +        if (parent.getChildAdapterPosition(view) == parent.getAdapter().getItemCount() - 1) {
`parent.getChildAdapterPosition(view)` в локальную переменную сохрани

2018-12-06 17:19 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/adapter/ContactItemDecoration.java
> +        if (parent.getChildAdapterPosition(view) == parent.getAdapter().getItemCount() - 1) {
вынесла в локальную переменную

2018-12-06 17:22 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/adapter/ContactAdapter.java
> +        new Thread(() -> {
добавила `task.interrupt()` в `onDestroyView()`
добавила в метод `run` проверку флага `Thread.currentThread().isInterrupted()`

2018-12-06 17:23 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/adapter/ContactAdapter.java
> +    private final List<Contact> contactsFull = new ArrayList<>();
Спасибо, так намного проще, чем мудрить с двумя списками
Добавила поиск на уровне `ContentResolver`

2018-12-13 12:23 UTC, RomanPozdeev requested changes

2018-12-13 12:23 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/ContactMapFragment.java
> +public final class ContactMapFragment extends MvpAppCompatFragment implements OnMapReadyCallback {
Можешь посмотреть на github moxy как они обыграли ситуацию с картой - в кратце можно сделать так чтобы вью аттачилась к презентеру только когда карта проинициализировалась.

2018-12-13 12:23 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/adapter/ContactAdapter.java
> +    private void updateItemsInternal(final List<Contact> newContacts) {
Лично я бы убрал все это из адаптера на уровень презентера

2018-12-13 12:23 UTC, RomanPozdeev commented on app/src/main/java/com/kkaysheva/ituniver/adapter/ContactAdapter.java
> +    private void updateItemsInternal(final List<Contact> newContacts) {
Или даже на уровень модели

2018-12-13 12:23 UTC, RomanPozdeev commented on app/src/main/res/layout/fragment_map.xml
> +    <fragment
MapView

2018-12-14 12:20 UTC, goblinr requested changes

2018-12-14 12:20 UTC, goblinr commented on app/src/main/java/com/kkaysheva/ituniver/model/ContactFetcher.java
> +                    contacts.add(new Contact(id, name, number, null));
Дублирование кода

2018-12-15 14:03 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/model/ContactFetcher.java
> +                    contacts.add(new Contact(id, name, number, null));
Вынесла в метод `getContactsFromCursor(Cursor cursor)`

2018-12-15 14:04 UTC, murrcha commented on app/src/main/res/layout/fragment_map.xml
> +    <fragment
Убрала `fragment`
Добавила `MapView`

2018-12-15 14:05 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactMapFragment.java
> +public final class ContactMapFragment extends MvpAppCompatFragment implements OnMapReadyCallback {
Нашла пример на котлине
https://gist.github.com/terrakok/cd080a6a0213ef7430bdd72ebe92c9ef
Это тот самый?

2018-12-16 06:40 UTC, goblinr approved these changes

2018-12-17 18:15 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/adapter/ContactAdapter.java
> +    private void updateItemsInternal(final List<Contact> newContacts) {
Убрала очередь
Сделала через `AsyncListDiffer`

2018-12-18 17:56 UTC, murrcha commented on app/src/main/java/com/kkaysheva/ituniver/ContactMapFragment.java
> +public final class ContactMapFragment extends MvpAppCompatFragment implements OnMapReadyCallback {
Сделала пока, как обычный фрагмент
В целом получается нужно сделать BaseMapFragment со своим MvpDelegate и использовать его во всех фрагментах где используется карта?

2018-12-30 10:31 UTC, merged